spring.application.name=sias-backend
# Conexão com o container do MySQL (db é o nome do serviço no docker-compose)
spring.datasource.url=jdbc:mysql://db:3306/sias_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=password123

# Hibernate: Cria as tabelas automaticamente no MySQL baseado nas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect